# Generated by Django 4.0.1 on 2022-01-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('title', models.TextField(db_column='Title')),
                ('album_id', models.AutoField(db_column='AlbumId', primary_key=True, serialize=False)),
                ('artist', models.IntegerField(db_column='ArtistId')),
            ],
            options={
                'db_table': 'albums',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('artist_id', models.AutoField(db_column='ArtistId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'artists',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.AutoField(db_column='TrackId', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('album', models.IntegerField(blank=True, db_column='AlbumId', null=True)),
                ('milliseconds', models.IntegerField(db_column='Milliseconds')),
            ],
            options={
                'db_table': 'tracks',
                'ordering': ('name',),
            },
        ),
    ]
