# Generated by Django 4.0.1 on 2022-01-27 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_track_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_albums', to='music.artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='related_tracks', to='music.album'),
        ),
    ]
