# Generated by Django 4.0.1 on 2022-01-30 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_album_artist_alter_track_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='music.artist')),
            ],
        ),
    ]
