# Generated by Django 4.0.1 on 2022-01-30 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_artistimage_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistimage',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_images', to='music.artist'),
        ),
    ]
